/// <reference types="cypress" />

/**
 * End-to-end scenario:
 *   User A logs in, posts an idea
 *   User B logs in, views the idea, comments on it, requests to join
 *   User A accepts the join request
 *   Both verify the dashboard updates without a manual refresh
 *
 * The dashboard sync indicator must report "Live" (or fall back to "Polling")
 * and counters must change without the user pressing reload.
 *
 * Prerequisites (set via cypress.env or cypress.config.ts):
 *   USER_A_EMAIL / USER_A_PASSWORD
 *   USER_B_EMAIL / USER_B_PASSWORD
 *
 * Both users must already exist (auth flow tested separately).
 */

const ts = Date.now();
const IDEA_TITLE = `E2E Idea ${ts}`;
const IDEA_DESC = `Auto-generated by Cypress at ${new Date(ts).toISOString()}`;
const COMMENT_TEXT = `E2E comment ${ts}`;

describe("Innovation Hub ↔ Dashboard real-time sync", () => {
  const A_EMAIL = Cypress.env("USER_A_EMAIL");
  const A_PASS = Cypress.env("USER_A_PASSWORD");
  const B_EMAIL = Cypress.env("USER_B_EMAIL");
  const B_PASS = Cypress.env("USER_B_PASSWORD");

  it("posts → comments → join request → accept → dashboard updates without refresh", () => {
    // ---------- USER A: post idea ----------
    cy.loginAs(A_EMAIL, A_PASS);
    cy.visit("/dashboard");

    // Capture baseline counters from data-value attributes (no parsing needed)
    cy.get('[data-testid="stat-ideas"]', { timeout: 15000 })
      .invoke("attr", "data-value")
      .then((v) => cy.wrap(parseInt(v || "0", 10)).as("baselineIdeasA"));
    cy.get('[data-testid="stat-notifications"]')
      .invoke("attr", "data-value")
      .then((v) => cy.wrap(parseInt(v || "0", 10)).as("baselineNotifsA"));

    // Sync indicator must be present and reach a healthy state
    cy.get('[data-testid="sync-status"]', { timeout: 15000 })
      .should("be.visible")
      .invoke("attr", "data-status")
      .should("match", /^(live|polling)$/);

    // Go to Innovation Hub and post an idea
    cy.visit("/innovation-hub");
    cy.contains("button", /post (an )?idea|new idea/i).click();
    cy.get('input[name="title"], input[placeholder*="title" i]').first().type(IDEA_TITLE);
    cy.get('textarea[name="description"], textarea[placeholder*="describe" i]').first().type(IDEA_DESC);
    cy.contains("button", /post|submit|create/i).last().click();

    // Confirm idea exists in the public feed
    cy.contains(IDEA_TITLE, { timeout: 15000 }).should("be.visible");

    // Without manual reload, dashboard idea counter should increment
    cy.visit("/dashboard");
    cy.get<number>("@baselineIdeasA").then((baseline) => {
      cy.get('[data-testid="stat-ideas"]', { timeout: 20000 }).should(($el) => {
        const n = parseInt($el.attr("data-value") || "0", 10);
        expect(n).to.be.gte(baseline + 1);
      });
    });

    // ---------- USER B: view, comment, join ----------
    cy.logout();
    cy.loginAs(B_EMAIL, B_PASS);
    cy.visit("/innovation-hub");

    cy.contains(IDEA_TITLE, { timeout: 15000 }).click();

    // Comment
    cy.get('textarea[placeholder*="comment" i], textarea[placeholder*="message" i]')
      .first()
      .type(COMMENT_TEXT);
    cy.contains("button", /send|post|comment/i).first().click();
    cy.contains(COMMENT_TEXT, { timeout: 10000 }).should("be.visible");

    // Request to join
    cy.contains("button", /request to join|join team|join/i).first().click();
    cy.get('textarea').first().type(`E2E join request ${ts}`, { force: true });
    cy.contains("button", /send request|request|submit/i).last().click();

    // ---------- USER A: accept request, no refresh ----------
    cy.logout();
    cy.loginAs(A_EMAIL, A_PASS);
    cy.visit("/dashboard");

    // Capture notification baseline (should rise after acceptance triggers a notif to B,
    // and A's own notifications may also bump from comment events depending on triggers).
    cy.get('[data-testid="stat-notifications"]')
      .invoke("attr", "data-value")
      .then((v) => cy.wrap(parseInt(v || "0", 10)).as("notifsBeforeAccept"));

    // Capture teams baseline before accepting (should increment when A is auto-added as founder)
    cy.get('[data-testid="stat-teams"]')
      .invoke("attr", "data-value")
      .then((v) => cy.wrap(parseInt(v || "0", 10)).as("teamsBeforeAccept"));

    // Navigate to Join Requests panel — request should appear via realtime
    cy.contains("button", /join requests/i).click();
    cy.contains(IDEA_TITLE, { timeout: 20000 }).should("be.visible");
    cy.contains("button", /accept/i).first().click();

    // Verify the request disappears AND collaborations panel reflects new member
    cy.contains(IDEA_TITLE).should("not.exist");
    cy.contains("button", /collaborations/i).click();
    cy.contains(IDEA_TITLE, { timeout: 20000 }).should("be.visible");

    // Teams counter should bump without refresh (A becomes founder of new team)
    cy.get<number>("@teamsBeforeAccept").then((baseline) => {
      cy.get('[data-testid="stat-teams"]', { timeout: 20000 }).should(($el) => {
        const n = parseInt($el.attr("data-value") || "0", 10);
        expect(n).to.be.gte(baseline + 1);
      });
    });
  });

  it("dashboard sync indicator transitions through valid states", () => {
    cy.loginAs(A_EMAIL, A_PASS);
    cy.visit("/dashboard");
    cy.get('[data-testid="sync-status"]', { timeout: 15000 })
      .should("be.visible")
      .invoke("attr", "data-status")
      .should("match", /^(connecting|live|polling)$/);
  });
});
