ALTER TABLE public.notes 
ADD COLUMN IF NOT EXISTS category text DEFAULT NULL,
ADD COLUMN IF NOT EXISTS university text DEFAULT NULL,
ADD COLUMN IF NOT EXISTS year integer DEFAULT NULL,
ADD COLUMN IF NOT EXISTS file_type text DEFAULT 'pdf';